# Base config
spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

---
# DEV
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

---
# PRD
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false